apiVersion: v1
kind: ConfigMap
metadata:
  name: bullmq-cm
data:
  REDIS_SERVER: redis
  REDIS_PORT: "6379"
---  
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: 'bullmq-worker'
  labels:
    app.openshift.io/runtime: nodejs
    deploymentconfig: 'bullmq-worker'
    app.kubernetes.io/name: 'bullmq-worker'
    app.kubernetes.io/part-of: bullmq
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    deploymentconfig: 'bullmq-worker'
    app.kubernetes.io/name: 'bullmq-worker'
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: 'bullmq-worker'
        app.kubernetes.io/name: 'bullmq-worker'
    spec:
      initContainers:
        - name: wait-for-redis
          imagePullPolicy: "IfNotPresent"
          image: busybox
          command:
          - /bin/sh
          - -c
          - >
            set -x;
            until nc redis 6379;
            do echo waiting for redis;
            sleep 2; done
      containers:
          - name: "bullmq-worker"
            image: "ceciliarb/benchmark-bullmq-worker:latest"
            imagePullPolicy: "IfNotPresent"
            resources:
              limits:
                memory: "512Mi"
              requests:
                cpu: 1
                memory: "512Mi"
            envFrom:
              - configMapRef:
                  name: bullmq-cm
  triggers:
    - type: ConfigChange
