kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "redis-data"
  namespace: teste-ceci
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: standard
  volumeMode: Filesystem
